#!/bin/sh

# NOTE: becomes .tmp_update/updater

# LessOS provides platform directly via environment variable
if [ -n "$LESSOS_PLATFORM" ]; then
	PLATFORM=$(echo "$LESSOS_PLATFORM" | tr '[:upper:]' '[:lower:]')
else
	# Stock OS - detect platform from cpuinfo
	INFO=$(cat /proc/cpuinfo 2>/dev/null)
	case $INFO in
	*"sun8i"*)
		if [ -d /usr/miyoo ]; then
			PLATFORM="my282" # Miyoo A30
		else
			PLATFORM="trimuismart"
		fi
		;;
	*"SStar"*)
		PLATFORM="miyoomini"
		;;
	*"TG5040"*|*"TG3040"*)
		PLATFORM="tg5040" # Trimui Smart Pro or Brick
		;;
	*"0xd03"*)
		PLATFORM="zero28" # MagicX Mini Zero 28
		;;
	*"0xd05"*)
		PLATFORM="my355" # Miyoo Flip
		;;
	esac

	# fallback for tg5040 20240413 recovery firmware
	# TODO: doublecheck interaction with tg3040
	# might need/want to strings /usr/trimui/bin/MainUI during install/update
	# and store platform in a text file
	if [ -z "$PLATFORM" ] && [ -f /usr/trimui/bin/runtrimui.sh ]; then
		PLATFORM="tg5040"
	fi
fi

# Use LessOS storage path if set, otherwise default to stock path
SDCARD_PATH="${LESSOS_STORAGE:-/mnt/SDCARD}"

exec "$SDCARD_PATH/.tmp_update/$PLATFORM.sh" # &> $SDCARD_PATH/boot.txt
